-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mar. 14 fév. 2023 à 15:28
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `voyages`
--

DROP TABLE IF EXISTS `voyages`;
CREATE TABLE IF NOT EXISTS `voyages` (
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `capitalcity` varchar(255) NOT NULL,
  `continent` varchar(255) NOT NULL,
  `population` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `voyages`
--

INSERT INTO `voyages` (`name`, `description`, `id`, `capitalcity`, `continent`, `population`) VALUES
('Afrique du Sud', ' Nation aux phénotypes très variés, l\'Afrique du Sud est ainsi en Afrique le pays présentant la plus grande portion de populations dites coloureds, blanches et Asiatiques. Elle est souvent appelée « nation arc-en-ciel », notion inventée par l\'archevêque Desmond Tutu pour désigner la diversité de la nation sud-africaine et qui a remplacé le concept de société plurale employé précédemment par les théoriciens de l\'apartheid (1948-1991).\r\n\r\nL\'égalité des revenus entre les différents groupes de populations n\'a pas progressé depuis la fin de l\'apartheid et l\'Afrique du Sud connaît un taux d\'inégalité parmi les plus élevés au monde. C\'est toutefois une puissance de référence pour le continent africain avec l\'une des économies les plus développées du continent et des infrastructures modernes couvrant tout le pays. C\'est la deuxième puissance économique d\'Afrique derrière le Nigeria. Le pays se caractérise aussi par une importante population de souche européenne (Afrikaners, Anglo-sud-africains) et par d\'importantes richesses minières (or, diamant, charbon, etc.) qui en ont fait un allié indispensable des pays occidentaux durant la guerre froide.', 1, 'Capitale administrative : Pretoria', 'Continent : Afrique', 'Population : 57,72 millions d\'habitants'),
('Algérie', ' Avec une superficie de 2 381 741 km2, c\'est à la fois le plus grand pays d\'Afrique, du monde arabe et du bassin méditerranéen. Il partage plus de 6 385 km de frontières terrestres, avec la Tunisie au nord-est, la Libye à l\'est, le Niger au sud-est, le Mali au sud-ouest, la Mauritanie et le Sahara occidental à l\'ouest, et enfin le Maroc au nord-ouest.\r\n\r\nDes sites archéologiques ont révélé des traces d’hominidés datant de près de deux millions d’années. Dans l\'Antiquité, le territoire algérien connaît la formation des royaumes numides avant de passer sous la domination partielle des Romains, des Vandales, des Byzantins et des principautés berbères indépendantes. Le viie siècle marque le début de l\'islamisation puis l\'arabisation partielle de la population. Le Maghreb central connaît alors plusieurs dynasties locales : Rostémides, Zirides, Hammadides, Zianides et des périodes d\'intégration dans des groupements impériaux plus larges.', 2, 'Capitale : Alger', 'Continent : Afrique', 'Population : 44,6 millions d\'habitants'),
('Allemagne', 'L\'Allemagne est le pays le plus peuplé de l\'Union européenne. Elle est une grande puissance politique et ses dirigeants politiques successifs sont parmi les personnalités politiques les plus influentes de l\'Union européenne. L\'Allemagne est aussi la première puissance économique d\'Europe ainsi que la quatrième puissance économique mondiale, et elle compte parmi les pays industrialisés les plus développés et les plus performants dans le monde. Elle figure parmi les premiers mondiaux dans les secteurs de l\'aéronautique, de l\'automobile, de l\'industrie chimique et de la construction mécanique. L\'Allemagne est en 2017 le troisième exportateur mondial derrière la Chine et les États-Unis et elle est le pays présentant le plus grand excédent commercial du monde en 2018. Elle a aussi le taux de chômage le plus bas parmi les 19 États membres de la zone euro, ce taux s\'établissant à 3,3 % en décembre 2018, d\'après Eurostat. L\'Allemagne affiche un niveau de vie « très élevé » : elle est 9e au classement IDH en 2021.', 3, 'Capitale : Berlin', 'Continent : Europe', 'Population : 84 millions d\'habitants'),
('Angleterre', ' Le centre et le sud de l\'Angleterre sont principalement constitués de basses collines et de plaines, tandis que le nord (avec le district du Lac et les Pennines) et l\'ouest (avec le Dartmoor et les collines (en) du comté de Shrops) sont principalement constitués de hautes terres montagneuses. La capitale est Londres, qui constitue la plus grande aire métropolitaine du Royaume-Uni. La population de l\'Angleterre est de 56,3 millions d\'habitants, et elle comprend plus de 84 % de la population britannique. Elle est largement concentrée autour de Londres, dans le Sud-Est, dans les conurbations des Midlands, au Nord-Ouest, au Nord-Est, et dans le comté d\'York. Chacune d\'entre elles s\'est développée en tant que grande région industrielle, au cours du xixe siècle.\r\n\r\nLe Royaume d\'Angleterre (auquel s\'ajoute le Pays de Galles après 1542) cessa d\'être un État souverain le 1er mai 1707, lorsque les Actes d\'Union mirent en vigueur les accords convenus dans le traité d\'Union de l\'année précédente. Ils menèrent à une union politique avec le Royaume d\'Écosse, pour former le Royaume de Grande-Bretagne. En 1801, la Grande-Bretagne s\'unifia avec le Royaume d\'Irlande, à travers un autre Acte d\'Union, pour devenir le Royaume-Uni de Grande-Bretagne et d\'Irlande. En 1922, l\'État libre d\'Irlande fit sécession du Royaume-Uni, ce qui l\'a conduit à être renommé « Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord ». Le nom d\'« Angleterre » est fréquemment employé, par abus de langage, pour désigner le Royaume-Uni dans son ensemble.', 4, 'Capitale : Londres', 'Continent : Europe', 'Population : 56,3 millions d\'habitants'),
('Argentine', ' La langue prédominante est l\'espagnol, dans sa variante rioplatense, la monnaie est le peso argentin et la principale religion est le catholicisme. D\'une superficie de 2 791 810 km2, l\'Argentine a une densité de population de seize habitants par kilomètre carré.\r\n\r\nL\'Argentine fait partie des pays dits du Cône Sud et parmi les pays d\'Amérique latine, il est, avec l\'Uruguay et le Chili, celui où la culture européenne est la plus affirmée. L\'Argentine est l\'un des pays les plus développés du continent latino-américain. Le pays est également la troisième puissance économique d\'Amérique latine après le Brésil et le Mexique, que ce soit en PIB nominal ou à parité de pouvoir d\'achat (PPA). Il connaît cependant une crise économique depuis la fin des années 2010, marquée par une forte inflation et la hausse de la pauvreté.', 5, 'Capitale : Buenos Aires', 'Continent : Amérique de Sud', 'Population : 43 millions d\'habitants'),
('Australie', 'L\'Australie est un pays développé avec une économie à revenu élevé. Ses ressources naturelles abondantes et ses relations commerciales internationales développées sont essentielles pour son économie, qui génère des revenus à partir des services, des exportations minières, de la banque, de l\'industrie manufacturière, de l\'agriculture et de l\'éducation internationale. En 2022, l\'Australie est la douzième économie mondiale avec le neuvième revenu par habitant le plus élevé. L\'Australie est une puissance régionale et possède la treizième plus grande dépense militaire au monde.\r\n\r\nL\'Australie figure en haut des classements internationaux en termes de qualité de vie, de démocratie, de santé, d\'éducation, de liberté économique, de libertés publiques, de sécurité et de droits politiques. En 2017, elle est classée au cinquième rang de l\'indice de développement humain. En 2022, elle est classée en 25e position pour l\'indice mondial de l\'innovation. Plusieurs de ses grandes villes figurent dans les classements des villes les plus agréables à vivre. ', 6, 'Capitale : Canberra', 'Continent : Océanie', 'Population : 26 millions d\'habitants'),
('Canada', 'Le Canada est une monarchie constitutionnelle et une démocratie parlementaire s\'inscrivant dans la tradition de Westminster. Le chef du gouvernement est le premier ministre et il est nommé par le gouverneur général, représentant le monarque, qui est le chef d\'État. Le pays est un royaume du Commonwealth. Il figure en haut des classements internationaux en termes de transparence gouvernementale, de libertés civiles, de qualité de vie, de liberté économique et d\'éducation. En 2021, la population canadienne est de près de 37 millions d\'habitants. La majorité de la population est blanche, mais elle comporte également plusieurs minorités raciales, en raison d\'une diversification de l\'immigration depuis l\'introduction du multiculturalisme en 1971.\r\n\r\nEn tant que pays développé, le Canada possède le 24e PIB nominal par habitant le plus élevé au monde et occupe le quinzième rang en termes d\'indice de développement humain. Son économie est dixième au niveau mondial et est principalement basée sur d\'abondantes ressources naturelles, ainsi que sur des réseaux commerciaux internationaux développés.', 7, 'Capitale : Ottawa', 'Continent : Amérique du Nord', 'Population : 37 millions d\'habitants'),
('Chine', 'La Chine est l\'une des plus anciennes civilisations au monde, et est parfois citée comme la plus ancienne civilisation continue. Elle trouve son origine dans la vallée du fleuve Jaune puis s\'est étendue vers le sud (conquête des territoires au sud du Yangtsé dès la dynastie Han), vers l\'ouest (premières incursions en Asie centrale sous les Han, extension temporaire jusqu\'à la mer Caspienne sous les Tang, conquête du Xinjiang et du Tibet sous les Qing) et vers le nord (la dynastie Qing, d\'origine mandchoue, apporta à la Chine la Mandchourie et la Mongolie). Au cours de son histoire la Chine a été à plusieurs reprises divisée puis réunifiée ; elle a été par deux fois entièrement conquise par des étrangers (par les Mongols au xiiie siècle et par les Mandchous au xviie siècle), bien que ceux-ci aient fini par adopter les coutumes et le système administratif chinois pour gouverner l\'empire. La dernière dynastie impériale, les Qing (la dynastie d\'origine mandchoue qui régnait sur le pays depuis 1644), a connu une période de déclin durant la phase d\'expansion coloniale des pays occidentaux, menant le pays de défaite en défaite à partir des guerres de l\'opium. ', 8, 'Capitale : Pékin', 'Continent : Asie', 'Population : 1;4 milliard d\'habitants'),
('Corée du Sud', 'La péninsule de Corée est baignée à l\'ouest par la mer Jaune, au sud par le détroit de Corée et à l\'est par la mer de l\'Est ou mer du Japon. La surface de la Corée du Sud couvre environ deux fois et demie celle de la Suisse.\r\n\r\nLarge en moyenne de 200 km, le territoire sud-coréen est composé à 70 % de montagnes, orientées dans l\'axe nord-sud, ce qui rend les communications est-ouest difficiles. Le volcan Halla (Hallasan), sur l\'île de Jeju, est le point culminant de la Corée du Sud, à 1 950 m d\'altitude. Aucun volcanisme n\'est actif en Corée, qui ne subit quasiment aucun tremblement de terre, même de faible ampleur. Sur le continent, le mont Jiri (Jirisan) (1 915 m) et le mont Seorak (Seoraksan) à 1 708 m sont les points culminants du pays. La chaîne du mont Seorak, très proche de la côte Est, fait barrage aux entrées maritimes depuis la mer du Japon et produit des hivers secs et froids sur le versant Ouest. Le versant Est subit de temps à autre des typhons venus de la mer du Japon. Sur cette face Est, les terrains sont profondément ravinés par les précipitations importantes, les galets constituent les lits des torrents et rivières. Le versant Ouest, peu érodé, présente des collines douces et des plaines agricoles aux sols riches. La côte est très découpée, parsemée de nombreuses îles et îlots. Les plages de la côte Est sont très appréciées ; par ailleurs la rencontre de deux courants marins au large des côtes rendent ces eaux très poissonneuses.\r\n\r\n\r\n', 9, 'Capitale : Séoul', 'Continent : Asie', 'Population : 50,5 millions d\'habitants'),
('Cuba', 'La république de Cuba est située entre la mer des Caraïbes au sud, le golfe du Mexique au nord-ouest, la Floride au nord et les Bahamas au nord-est, elles-mêmes baignées par l\'Atlantique Nord. Géographiquement, elle se trouve à proximité du tropique du Cancer, à 87 km à l\'ouest-nord-ouest de la pointe du Cheval Blanc, sur l\'île d\'Haïti; à 145 km au nord de la Jamaïque ; à 208 km de Punta Cayo Raton, sur la péninsule du Yucatán (Mexique), et à 212 km au sud de East Cape, sur la péninsule de Floride.\r\n\r\nC\'est un archipel composé de l\'île de Cuba, longue de 1 210 km (qui fait d\'elle la plus grande île des Antilles), de l\'île des Pins (île de la Jeunesse) et de 4 095 keys.\r\n\r\nLa République comprend l\'île entière ainsi que la Isla de la Juventud (« île de la Jeunesse »), mais l\'entrée de la baie de Guantánamo est occupée depuis 1898 (officiellement loué depuis 1903) par les États-Unis qui y ont installé une importante base navale (que les États-Unis maintiennent malgré l\'opposition du gouvernement cubain). De ce fait, Cuba et les États-Unis partagent une frontière terrestre longue de 29 km.', 10, 'Capitale : La Havane', 'Continent : Amérique du Sud', 'Population : 11 253 000 habitants'),
('Egypte', 'L\'Égypte a l\'une des plus longues histoires de tous les pays. Berceau de la civilisation, l\'Égypte antique a vu parmi les premiers développements de l\'écriture, l\'agriculture, le gouvernement centralisé et la religion organisée au cours de plus de trois millénaires avant l\'Ère commune. Des monuments emblématiques tels le Sphinx de Gizeh, les pyramides de Gizeh et la vallée des Rois reflètent cet héritage et demeurent des sources importantes d\'intérêt scientifique et populaire. Pendant la période de domination romaine, l\'Égypte est devenu l\'un des premiers centres du christianisme avant d\'être islamisée par les conquêtes arabes du viie siècle. L\'Égypte demeure un pays principalement musulman avec une minorité chrétienne importante.', 11, 'Capitale : Le Caire', 'Continent : Afrique du Nord-Est', 'Population : 102 millions d\'habitants'),
('Etats-Unis', ' Le pays s\'étend sur 9,8 millions de kilomètres carrés, ce qui en fait, selon les critères, le troisième ou quatrième pays du monde en superficie après la Russie, le Canada et la Chine. La population américaine augmente grâce à un solde naturel et à un solde migratoire positifs. Elle est marquée par une grande diversité ethnique en raison d\'une immigration ancienne et diversifiée. L\'économie nationale, de type capitaliste, est la plus importante au monde, avec le PIB le plus élevé en 2022 ; elle est notamment alimentée par une productivité du travail élevée.\r\n\r\nLes secteurs qui reflètent la puissance américaine sont l\'agriculture, les industries de pointe et les services. L\'économie américaine est aussi l\'une des plus grandes manufacturières du monde. Le pays représente 37 % de la dépense militaire mondiale ; il est aussi une force politique et culturelle majeure ainsi qu’un leader mondial dans la recherche scientifique et l\'innovation technologique.\r\n\r\n\r\n', 12, 'Capitale : Washington', 'Continent : Amérique du Nord', 'Population : 331 millions d\'habitants'),
('Espagne', 'L\'Espagne est bordée au nord-est par les Pyrénées, qui constituent une frontière naturelle avec la France et l\'Andorre ; à l\'est et au sud-est par la mer Méditerranée, au sud-sud-ouest par le territoire britannique de Gibraltar et le détroit du même nom, ce dernier séparant le continent européen de l\'Afrique. Le Portugal est limitrophe de l\'Espagne à l\'ouest tandis que l\'océan Atlantique borde le pays à l\'ouest-nord-ouest ; enfin le golfe de Gascogne baigne le littoral nord. Le territoire espagnol inclut également les îles Baléares en Méditerranée, les îles Canaries dans l\'océan Atlantique au large de la côte africaine, et deux villes autonomes en Afrique du Nord, Ceuta et Melilla, limitrophes du Maroc.', 13, 'Capitale : Madrid', 'Continent : Europe', 'Population : 47 millions d\'habitants'),
('France', ' La partie européenne de la France, appelée France métropolitaine, est située à l\'extrémité occidentale de l\'Europe, et sa délimitation est restée inchangée depuis la fin de la Seconde Guerre mondiale et le traité de Paris en 1947. Elle est bordée par la mer du Nord au nord, la Manche au nord-nord-ouest, la mer Celtique à l\'ouest-nord-ouest, le golfe de Gascogne à l\'ouest et la mer Méditerranée au sud-est. Elle est frontalière de la Belgique au nord-nord-est, du Luxembourg au nord-est, de l\'Allemagne à l\'est-nord-est, de la Suisse à l\'est, de l\'Italie à l\'est-sud-est, de Monaco au sud-est et de l\'Espagne et Andorre au sud-sud-ouest.\r\n\r\nLes frontières à l\'est, au sud-est et au sud-ouest du territoire métropolitain sont établies en s\'appuyant sur des cours d\'eau et des massifs montagneux, à savoir le Rhin, le Jura, le Léman, les Alpes et les Pyrénées, tandis qu\'au nord-est la frontière ne se fonde pas sur des éléments naturels.\r\n\r\nLa France est également composée de nombreux territoires situés en dehors du continent européen, couramment appelés France d\'outre-mer, qui lui permettent d\'être présente dans tous les océans du monde sauf l\'océan Arctique.', 14, 'Capitale : Paris', 'Continent : Europe', 'Population : 67,8 millions d\'habitants'),
('Guinée', 'La Guinée est une république. Son président, directement élu par le peuple, est chef de l\'État et nomme un Premier ministre qui est chef du gouvernement. L\'Assemblée nationale monocamérale est le corps législatif du pays et ses membres sont également directement élus par le peuple. Le pouvoir judiciaire est dominé par la Cour suprême de Guinée, plus haute cour d\'appel du pays.\r\n\r\nLa Guinée est un pays à prédominance musulmane, avec 85 % de la population. La population guinéenne se répartit en plusieurs groupes ethniques. Le français, langue officielle de la Guinée, est la principale langue de communication dans les écoles, l\'administration publique et les médias. Mais plus de 24 langues nationales, dont le poular, le malinké, le soussou, le guerzè, le toma et le kissi sont largement parlées comme langues d\'échanges plus communs entre les populations.\r\n\r\nL\'économie guinéenne est largement tributaire de l\'agriculture et de la production minière. En 2014, elle est le sixième plus grand producteur mondial de bauxite et possède des réserves de diamants et d\'or.', 15, 'Capitale : Conakry', 'Continent : Afrique de l\'Ouest', 'Population : 13 885 724 habitants'),
('Inde', 'L\'Inde est le deuxième pays le plus peuplé et le septième pays le plus grand du monde. Le littoral indien s\'étend sur plus de sept mille kilomètres. Le pays a des frontières communes avec le Pakistan au nord-ouest, la Chine au nord et à l\'est-nord-est, le Népal au nord-est, le Bhoutan, le Bangladesh et la Birmanie à l\'est-nord-est. Sur l\'océan Indien, l\'Inde est à proximité des Maldives au sud-sud-ouest, du Sri Lanka au sud et de l\'Indonésie au sud-est. L\'Inde revendique également une frontière avec l\'Afghanistan au nord-ouest. L\'Inde dispose de l\'arme nucléaire depuis 1974 après avoir fait des essais officiels.\r\n\r\nL\'Inde est un foyer de civilisations parmi les plus anciennes du monde, la civilisation de la vallée de l\'Indus s\'y est développée dès 3000 av. J.-C.. Le sous-continent indien a abrité de vastes empires et est présent sur les routes commerciales dès l\'Antiquité. L\'Inde est la terre de naissance de quatre religions majeures — l\'hindouisme, le jaïnisme, le bouddhisme et le sikhisme — alors que le zoroastrisme, le christianisme et l\'islam s\'y sont implantés durant le Ier millénaire.\r\n\r\nL\'hindouisme y est la religion majoritaire avec environ 80 % de fidèles. l\'Inde est le troisième pays ayant la communauté musulmane la plus importante.\r\n\r\nL\'Inde est aujourd\'hui un pays très divers sur le plan religieux, linguistique et culturel.', 16, 'Capitale : New Delhi', 'Continent : Asie', 'Population : 1 326 093 247 habitants'),
('Italie', 'C\'est un pays d\'Europe du Sud correspondant physiquement à une partie continentale, une péninsule située au centre de la mer Méditerranée et une partie insulaire constituée par les deux plus grandes îles de cette mer, la Sicile et la Sardaigne, et beaucoup d\'autres îles plus petites — hormis la Corse, cédée par la République de Gênes à la France en 1768. Elle est rattachée au reste du continent par le massif des Alpes. Le territoire italien correspond approximativement à la région géographique homonyme.\r\n\r\nL\'Italie apporte une contribution très importante à la civilisation occidentale : elle est notamment le berceau de la civilisation étrusque, de la Grande-Grèce, de l\'Empire romain, du Saint-Siège, des républiques maritimes, de l\'humanisme et de la Renaissance. Existant en tant qu\'État unitaire depuis 1861 à la suite du Risorgimento (Renaissance ou Résurrection) mené par le royaume de Sardaigne, l\'Italie est une république depuis l\'abolition par référendum de la monarchie italienne en 1946. Elle est membre fondateur de l\'Union européenne et de la zone euro.\r\n\r\nL\'Italie est, en ce début de xxie siècle, une puissance moyenne, forte de ses soixante millions d\'habitants, de sa position en 2017 de huitième puissance économique mondiale et de troisième économie de la Zone Euro, et de son rôle au sein de nombreuses organisations internationales comme l\'Union européenne, l\'Organisation du traité de l\'Atlantique nord, le G7 et l\'Organisation de coopération et de développement économiques.', 17, 'Capitale : Rome', 'Continent : Europe', 'Population : 59 030 133 habitants'),
('Japon', 'Le Japon est la troisième puissance économique du monde pour le PIB nominal et la quatrième pour le PIB à parité de pouvoir d\'achat. Ce dynamisme économique s\'appuie surtout sur une industrie performante et innovante, portée par de grands groupes d\'importance mondiale appelés Keiretsu , tout particulièrement dans les secteurs de la construction automobile (troisième producteur mondial en 2017) ou de l\'électronique de pointe. Il est aussi le quatrième pays exportateur et le sixième pays importateur au monde. Acteur majeur du commerce international et puissance épargnante, il a ainsi accumulé une position créancière nette vis-à-vis du reste du monde (en) de plus de 325 000 milliards de yens, le plaçant en première position devant la Chine. C\'est un pays développé, avec un niveau de vie très élevé (dix-neuvième IDH le plus élevé en 2021), de faibles inégalités (le troisième IDH ajusté aux inégalités le plus élevé, toujours en 2018) et la plus longue espérance de vie au monde selon les estimations de l\'ONU. En 2022, le Japon est classé en 13e position pour l\'indice mondial de l\'innovation. Mais ce tableau idyllique ne doit pas masquer d\'importants problèmes qui pèsent sur l\'avenir du pays : le Japon souffre d\'un des taux de natalité les plus bas du monde, très en dessous du seuil de renouvellement des générations. Le pays est actuellement en déclin démographique. C\'est également le pays pour lequel le poids de la dette publique brute est le plus important au monde, cette dernière s\'élève en 2017 à 240 % du PIB.', 18, 'Capitale : Tokyo', 'Continent : Asie', 'Population : 125 104 000 habitants'),
('Maroc', 'Le Maroc possède une flore riche du fait de sa position stratégique. En effet, il possède deux façades maritimes totalisant plus de 3 500 km, dont 500 en mer Méditerranée. Il reçoit de ce fait les courants chargés de pluie de l\'océan qui s\'accumulent contre la barrière montagneuse de l\'Atlas, ce qui permet de fortes précipitations à Rabat, Casablanca, Fès et la formation des neiges à Ifrane et Azrou et dans les hauts sommets de l\'Atlas, pendant que le sud et l\'est restent arides.\r\n\r\n\r\nCédraie, région d\'Ifrane.\r\nPlus de 4 500 espèces configurent la flore marocaine. Les variations du climat et du relief sont des éléments fondamentaux pour expliquer une telle richesse florale. L\'intérêt botanique du Maroc est intense et on citera seulement les 2 500 000 hectares de forêt qui contiennent des cèdres, des palmiers, des thuyas, des dattiers, des amandiers, des figuiers, des oliviers, des acacias, des fruitiers, des chênes verts, des chênes-lièges, des pins, l\'eucalyptus, des arbousiers, l\'alfa et l\'endémique arganier, dont le Maroc est le seul pays au monde à disposer de cette espèce qui est inscrite au patrimoine mondial de l\'Unesco. La forêt représente environ 15 % de la surface totale.', 19, 'Capitale : Rabat', 'Continent : Afrique du Nord', 'Population : 37 344 787 habitants'),
('Mexique', 'Le Mexique fait partie des vingt premières puissances économiques mondiales (quinzième avec un PIB nominal de 1 149 milliards de dollars en 2017). Mesuré en parité de pouvoir d\'achat, son PIB arrive à la onzième place, derrière la France (dixième).\r\n\r\nEn 2019, le Mexique est le douzième plus grand producteur de pétrole au monde et le premier producteur d\'argent. Puissance émergente, puissance moyenne à l\'échelle mondiale et puissance régionale en Amérique latine, le Mexique est le premier pays d\'Amérique latine à avoir rejoint l\'OCDE. Classé parmi les nouveaux pays industrialisés, il s\'agit, selon la Banque mondiale, d\'un pays à revenu intermédiaire supérieur.\r\n\r\nSon économie est fortement liée à celle des États-Unis, par son appartenance à l\'ALENA jusqu’en 2018 et le nouvel ACEUM (T-MEC en espagnol) après 2018.\r\n\r\nEn 2018, le Mexique est la deuxième destination touristique des Amériques et la première, devançant les États-Unis en 2021.', 20, 'Capitale : Mexico', 'Continent : Amérique du Sud', 'Population : 129 150 971 habitants');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
